sudo: required

language: python
python:
  - "3.8"

language: shell

env:
  global:
  - IDCODE=$TRAVIS_BUILD_DIR/
  - IDprediction=pwd>>$TRAVIS_BUILD_DIR/filelocation.txt&&$TRAVIS_BUILD_DIR/Run.sh

script:
  - chmod +x INSTALL.sh
  - source INSTALL.sh
  - chmod +x Run.sh
  - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt
  - $TRAVIS_BUILD_DIR/Run.sh -b CCC
  - $IDprediction
  - $IDprediction -c .1 -t trainset.csv

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov
