env:
  global:
        - IDCODE="/home/travis/build/pragneshrana/Deploy_DDS/"
        - PATH=$PATH:$IDCODE
        - IDprediction='$PWD>/home/travis/build/pragneshrana/Deploy_DDS/filelocation.txt && Run.sh'  
os:
  - linux
  
language: shell

install:
  - chmod +x INSTALL.sh
  - chmod +x Run.sh 
  - ls
  - echo $PWD
  - echo $IDprediction
  
script:
  - $IDprediction -b CCCC 
  - $IDprediction -c .1 -t trainset.csv 
  
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov

