sudo: required

env:
  global:
  - IDCODE=$TRAVIS_BUILD_DIR
  - IDprediction=pwd>>$TRAVIS_BUILD_DIR/filelocation.txt $TRAVIS_BUILD_DIR/Run.sh

language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - activate
  - conda config --env --add channels conda-forge
  - conda install -c conda-forge rdkit
  - conda install numpy
  - conda install scipy
  - conda install matplotlib
  - conda install pandas
  - conda install regex
  - conda install -c conda-forge random2
  - conda install python3-seaborn
  - conda install -c conda-forge scikit-learn
  - conda install -c conda-forge coveralls
  - conda install -c conda-forge codecov
  - conda install -c conda-forge latex
  - activate
  - sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended

  
language: shell

script:
  - chmod +x INSTALL.sh
  - chmod +x Run.sh
  - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt
  - $TRAVIS_BUILD_DIR/Run.sh -b CCC
  - $IDprediction -c 0.1 -t trainset.csv

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov
