sudo: required

env:
  global:
  - IDCODE=$TRAVIS_BUILD_DIR
  # - IDprediction=$PWD>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh

language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.8"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda env list
  - conda info -a
  - conda create --name prr python=3.8
  - conda activate prr
  - conda install -n prr -c conda-forge rdkit
  - conda install -n prr numpy
  - conda install -n prr scipy
  - conda install -n prr pandas
  - conda install -n prr regex
  - conda install -n prr -c conda-forge statsmodels
  - conda install -n prr -c conda-forge scikit-learn
  - conda install -n prr -c conda-forge coveralls
  - conda install -n prr -c conda-forge codecov
  # - sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended

  
language: shell

script:
  - chmod +x INSTALL.sh

  - chmod +x Run.sh
  - cd TryYourself/nAlkaneIDT/

  - echo 'Analyzing Data'
  - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -a trainset.csv

  # - echo 'Checking Bond Details for Heptane'
  # - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -b CCCCCCC

  # - echo 'Generating Histograms of parameters for each fuel'
  # - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -h trainset.csv

  - echo 'Multiple regression'
  - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -c 0.05 -r False -m alkane.csv

  # - echo 'Multiple regression with significance and feature elimination'
  # - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -c 0.05 -r True -s 0.05 -m alkane.csv

  # - echo 'Clustering tree based regression'
  # - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -c 0.05 -r False -t alkane.csv

  # - echo 'External test'
  # - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -e testset.csv

  # - cd ..
  # - cd BostonHousingPrice/

  # - echo 'Boston Hosing Price Data'
  # - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -c 0.1 -o trainset.csv
  # - pwd>>$TRAVIS_BUILD_DIR/filelocation.txt;$TRAVIS_BUILD_DIR/Run.sh -e testset.csv

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov
