sudo: required

language: shell

install:
  - dirPath=$PWD
  - echo $PWD
  - echo "export IDCODE='/home/travis/build/pragneshrana/Deploy_DDS'">~/.bashrc
  - echo "export PATH=$PATH:$IDCODE">~/.bashrc
  - echo "alias IDprediction='pwd>/home/travis/build/pragneshrana/Deploy_DDS/filelocation.txt && Run.sh'">~/.bashrc
  - cd
  - source .bashrc
  - cat .bashrc
  - cd $dirPath

script:
     
  - chmod +x INSTALL.sh
  - chmod +x Run.sh  
  - cd ./TryYourself/nAlkaneIDT
  - IDprediction -b CCC
  - IDprediction -c .1 -t trainset.csv 

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov
