sudo: required

env:
  global:
  - IDCODE=$TRAVIS_BUILD_DIR/
  - IDprediction=pwd>>$TRAVIS_BUILD_DIR/filelocation.txt&$TRAVIS_BUILD_DIR/Run.sh

language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"

install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  # - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  #     wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  #   else
  #     wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  #   fi
  # - bash miniconda.sh -b -p $HOME/miniconda
  # - source "$HOME/miniconda/etc/profile.d/conda.sh"
  # - hash -r
  # - conda config --set always_yes yes --set changeps1 no
  # - conda update -q conda
  # # Useful for debugging any issues with conda
  # - conda info -a

  - sudo apt-get install build-essential
  - sudo apt-get install python3-pip
  - sudo apt-get install python-rdkit librdkit1 rdkit-data
  - sudo apt-get install python3-tk
  - sudo apt-get install python3-numpy
  - sudo apt-get install python3-scipy
  - sudo apt-get install python3-matplotlib
  - sudo apt-get install python3-pandas
  - sudo apt-get install python3-regex
  - pip install --user collections-extended
  - pip install --user random2
  - sudo apt-get install python3-seaborn
  - pip install --user scikit-learn
  - pip install --user coveralls
  - pip install --user codecov
  - pip install --user latex
  - sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended
  
python:
  - "3.8"
  
language: shell

script:
  - chmod +x INSTALL.sh
  - chmod +x Run.sh
  - $TRAVIS_BUILD_DIR/Run.sh -b CCC
  - $IDprediction -c .1 -t trainset.csv

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov
