sudo: required

language: shell

env:
  global:
  - IDCODE=$TRAVIS_BUILD_DIR/Deploy_DDS/
  - IDprediction=pwd>>$TRAVIS_BUILD_DIR/Deploy_DDS/filelocation.txt && $TRAVIS_BUILD_DIR/Deploy_DDS/Run.sh

script:
  - ls
  - pwd
  - chmod +x INSTALL.sh
  - chmod +x Run.sh
  - source INSTALL.sh
  - pwd>>$TRAVIS_BUILD_DIR/Deploy_DDS/filelocation.txt
  - $TRAVIS_BUILD_DIR/Deploy_DDS/Run.sh -b CCC
  - IDprediction
  - IDprediction -c .1 -t trainset.csv

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov
