env:
  global:
        - IDprediction='pwd>$PWD/Data_driven_Kinetics/filelocation.txt && Run.sh'
        
os:
  - linux
  
language: shell

install:
  - chmod +x INSTALL.sh
  - chmod +x Run.sh 
  - ls
  - echo $PWD
  - echo $IDprediction
script:
  - pwd>$IDprediction && Run.sh -b CCCC 
  - pwd>$IDprediction && Run.sh -c .1 -t trainset.csv 
  
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov

