sudo: required

language: shell

install:
  - echo "export IDCODE='$PWD'"
  - echo "export PATH=$PATH:$IDCODE"
  - echo "alias IDprediction='pwd>${IDCODE}/filelocation.txt && Run.sh'">~/.bashrc

script:
  - chmod +x INSTALL.sh
  - chmod +x Run.sh  
  - cd $IDCODE/TryYourself/nAlkaneIDT
  - IDprediction -b CCC
  - IDprediction -c .1 -t trainset.csv 

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov
