env:
  global:
        - IDCODE="/home/travis/build/pragneshrana/Deploy_DDS/"
        - PATH=$PATH:$IDCODE
        - IDprediction='pwd>/home/travis/build/pragneshrana/Deploy_DDS/filelocation.txt && /home/travis/build/pragneshrana/Deploy_DDS/Run.sh'  
os:
  - linux
  
language: shell

install:
  - echo $IDprediction
  - chmod +x INSTALL.sh
  - chmod +x Run.sh 
  - ls 
  - echo $PWD
  - IDprediction
  
script:
  - IDprediction -b CCCC 
  - IDprediction -c .1 -t trainset.csv 
  
after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov

