sudo: required

env:
  global:
  - IDCODE=$TRAVIS_BUILD_DIR/
  - IDprediction=pwd>>$TRAVIS_BUILD_DIR/filelocation.txt && $TRAVIS_BUILD_DIR/Run.sh

language: python

cache: pip

before_install:
  - sudo apt-get install build-essential
  - sudo apt-get install python3-pip
  - pip install --user rdkit-pypi
  - pip install --user numpy
  - pip install --user scipy
  - pip install --user matplotlib
  - pip install --user pandas
  - pip install --user regex
  - pip install --user collections-extended
  - pip install --user random2
  - pip install --user seaborn
  - pip install --user scikit-learn
  - pip install --user coveralls
  - pip install --user codecov
  - pip install --user latex
  - sudo apt-get install -y texlive texlive-latex-extra texlive-latex-recommended
  
python:
  - "3.8"
  
language: shell

script:
  - chmod +x INSTALL.sh
  - chmod +x Run.sh
  - $TRAVIS_BUILD_DIR/Run.sh -b CCC
  - $IDprediction -c .1 -t trainset.csv

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash)
  - codecov
